[tool.poetry]
name = "type-annotation"
version = "0.1.0"
description = ""
authors = ["Alex Akimenko <alex.akimenko@rokt.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
